config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'post_new',       to: 'posts#new',    as: 'p_new'
  post 'post_create',    to: 'posts#create', as: 'p_create'
  get  'post_index',     to: 'posts#index',  as: 'p_index'
  get  'post_show/:id',  to: 'posts#show',   as: 'p_show'
  get  'post_edit/:id',  to: 'posts#edit',   as: 'p_edit'
  patch  'post_update/:id',    to: 'posts#update',  as: 'p_up'
  delete 'post_delete/:id',    to: 'posts#destroy', as: 'p_des'
  post  'posts/:post_id/comment',    to: 'comments#create', as: 'p_com'
  post  'posts/:user_id/comment/:comment_id', to: 'replies#create', as: 'reply'
  post  'posts/:user_id/reply/:reply_id',     to: 'replies#re_rep', as: 'r_reply'
  get 'search', to: 'posts#search'
  resources :posts do
    resources :likes, only: [:create, :destroy]
    # resources :comments, only: [:create]
  end
  
  
  get  'user/new',       to: 'users#new',    as: 'u_new'
  post 'user/create',    to: 'users#create', as: 'u_create'
  get  'user/index',     to: 'users#index',  as: 'u_index'
  get  'user/show/:id',      to: 'users#show',   as: 'u_show'
  get  'user/edit',      to: 'users#edit',   as: 'u_edit'
  patch'user/update',    to: 'users#update', as: 'u_up'
  resources :users do
    get :search, on: :collection
  end
  
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  
  # get  '/user/:id/following',  to: 'users#following',  as: 'following_user_path'
  # get  '/user/:id/followers',  to: 'users#followers',  as: 'followers_user_path'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  # get 'messages/index/:sender_id', to:  'messages#index', as: 'm_index'
  # get 'messages/room/:sender_id/:receiver_id', to:  'messages#roomshow', as: 'm_show'
  # post 'send', to: 'messages#create', as: 'send' 
  # resources :messages
  
  resources :relationships,       only: [:create, :destroy]
  
  get 'search_func', to: 'search#search',  as: 'search_func'
  get 'search_s', to: 'search#sato', as: 'sato'
  
  get  'room/index/:id',               to: 'rooms#index',   as: 'room'
  get  'chat/:room_id',                to: 'rooms#chat',    as: 'exist_room'
  get  'chat/:sender_id/:receiver_id', to: 'rooms#chat',    as: 'chat'
  post 'message/send',                 to: 'messages#sending', as: 'm_send'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # 削除機能をつけたらユーザー削除とともにポストも削除
  # has_many :posts, dependent: :destroy
  has_many :direct_messages
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  has_many :rooms
  has_many :messages
  has_many :replies, class_name: 'Reply', foreign_key: :user_id, dependent: :destroy
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  mount_uploader :profile_image, ProfileImageUploader
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :index]
  before_action :correct_user,   only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to p_index_path
    else
      render :new
    end
  end
  
  def show
    p'show============'
    @user = User.find(params[:id])
    p'show_end=========='
  end
  
  def index
    @users = User.all.order(id: :asc)
  end
  
  def edit
    @user = User.find(current_user.id)
  end
  
  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to u_show_path(current_user.id)
    else
      render 'edit'
    end
  end
  
  def following
    @user = User.find(current_user.id)
  end
  
  def followers
    @user = User.find(current_user.id)
  end
  
  def search
    if params[:email].present?
      @users = User.where('email LIKE ?', "%#{params[:email]}%")
    else
      @users = User.none
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:email, :prefucture, :city, :profile_image, :password, :password_confirmation)
    end
    
    def correct_user
      @user = User.find(current_user.id)
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def post_params
      params.require(:post).permit(:title)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="container" style="margin-top: 15px">
  <%= form_for(@user, url: u_up_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :Email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :Password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :Password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    
    <%= f.submit "Save changes", class: "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container" style="margin-top: 15px">
    <h1>ユーザー一覧</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">email</th>
      <th scope="col">created</th>
      <th scope="col">updated</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <th><%= link_to user.email, u_show_path(user.id) %></td>
      <td><%= user.created_at %></td>
      <td><%= user.updated_at %></td>
    </tr>
    <% end %>
  </tbody>  
</table>
  </div>

app/views/users/new.html.erb
<div class="container" style="margin-top: 15px">
  <%= form_for(@user, url: u_create_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :Email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    
    <h1>郵便番号から住所検索</h1> 
  <label>郵便番号
    <input type="text" id="postcode" maxlength="8" placeholder="例:0000000">
  </label>
  <button id="btn">検索</button>
    
    <div class="form-group hide open">
      <%= f.label :prefucture, value="住所（都道府県）" %>
      <%= f.text_field :prefucture,  id: 'pref', class: 'form-control' %>
    </div>
    
    <div class="form-group hide open">
      <%= f.label :city, value="住所（市町村）" %>
      <%= f.text_field :city, id: 'city', class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :Password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :Password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.label :profile_image, value="プロフィール画像"%>
    <%= f.file_field :profile_image, accept: 'image/jpeg,image/gif,image/png' %>
    
    <%= f.submit "Member registration", class: "btn btn-primary btn-lg" %>
  <% end %>
</div>



<!--<div class="container" style="margin-top: 15px">-->
<!--    <form class="new_user" id="new_user" action="/create" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="FTPwe2KG47J8+jCn1V+IYjxxhdD30lTJFWAbExgMfsfzq7V6CR4jR5bFP8d/a29AYQjh3M5kaSDwzEpnBWPLnw==">-->
<!--  <div class="form-group">-->
<!--    <label for="exampleInputEmail1">Email</label> <p id="emailerror"></p>-->
<!--    <input class="form-control" id="email" oninput="count_text()" type="email" name="user[email]">-->
<!--  </div>-->
<!--  <div class="form-group">-->
<!--    <label for="exampleInputEmail1">Password</label>-->
<!--    <input class="form-control" id="password" oninput="count_text()" type="password" name="user[password]">-->
<!--  </div>-->
<!--  <div class="form-group">-->
<!--    <label for="exampleInputEmail1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Password reconfirmation</font></font></label>-->
<!--    <input class="form-control" id="confirmation" oninput="count_text()" type="password" name="user[password_confirmation]">-->
<!--  </div>-->
<!--  <button class="btn btn-primary btn-lg" id="btn" disabled=""><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Member registration</font></font></button>-->
  
<!--</form>-->
<!--<script>-->
<!--  const count_text = () => {-->
<!--    const email = document.getElementById("email").value;-->
<!--    const password = document.getElementById("password").value.length;-->
<!--    const confirmation = document.getElementById("confirmation").value.length;-->
<!--    if(!email.includes("@")){-->
<!--      document.getElementById("emailerror").innerHTML = "@以下を入力してください"-->
<!--    }else{-->
<!--      document.getElementById("emailerror").innerHTML = ""-->
<!--    }-->
<!--    if(email.length > 1 && password  > 1 && confirmation){-->
<!--      document.getElementById("btn").removeAttribute("disabled");-->
<!--    }else{-->
<!--      console.log("test")-->
<!--      document.getElementById("btn").setAttribute("disabled", true);-->
<!--    }-->
<!--  }-->
<!--</script>-->
<!--  </div>-->

<script>

$(function(){
  $('#btn').on('click', () => {
    event.preventDefault();
    $('.open').fadeIn();
    $.ajax({
      url: "https://zipcloud.ibsnet.co.jp/api/search?zipcode=" + $('#postcode').val(),
      dataType: 'jsonp',
    }).done((data) => {
      if (data.results) { 
        getData(data.results[0]);
      } else {
        alert('該当データが見つかりません');
      }
    }).fail((data) => {
      alert('通信に失敗しました');
    });
  });

  function getData(data) {
    $('#pref').val(data.address1);
    $('#city').val(data.address2);
    $('#address').val(data.address3);
  }
});
</script>

app/views/users/search.html.erb
<h1>User search</h1>
<%= form_with url: search_users_path, method: :get, local: true do |f| %>
  <%= f.text_field :email %>
  <%= f.submit :search %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="container" style="margin-top: 15px">
    <h1><%= @user.email %>の詳細ページ</h1>
    <% if @user.profile_image? %>
      <%= image_tag @user.profile_image.url %>
    <% else %>
      <%= image_tag ("rails.png") %>
    <% end %>

    <section class="stats">
      <%= render 'shared/stats' %>
      <%= render 'follow_form' if logged_in? %>
    </section>
    <section class="stats">
    <h3>いいねしている投稿</h3>
      <% @user.liked_posts.each do |post| %>
        <%= link_to post.user.email, u_show_path(post.user.id) %>
        <%= link_to post.content, p_show_path(post.id)%>
      <% end %>
    </section>
    <% unless current_user == @user %>
    <%= link_to 'メッセージを送る', chat_path(sender_id: current_user.id, receiver_id: @user.id) %>
    <% end %>
<h2>投稿一覧</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">title</th>
      <th scope="col">created</th>
      <th scope="col">updated</th>
    </tr>
  </thead>
  <tbody>
    <% @user.posts.each do |post| %>
    <tr>
      <th scope="row"><%= post.id %></th>
      <th><%= link_to post.title, p_show_path(post.id) %></td>
      <td><%= post.created_at %></td>
      <td><%= post.updated_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>
  </div>