config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'post_new',       to: 'posts#new',    as: 'p_new'
  post 'post_create',    to: 'posts#create', as: 'p_create'
  get  'post_index',     to: 'posts#index',  as: 'p_index'
  get  'post_show/:id',  to: 'posts#show',   as: 'p_show'
  get  'post_edit/:id',  to: 'posts#edit',   as: 'p_edit'
  patch  'post_update/:id',    to: 'posts#update',  as: 'p_up'
  delete 'post_delete/:id',    to: 'posts#destroy', as: 'p_des'
  post  'posts/:post_id/comment',    to: 'comments#create', as: 'p_com'
  post  'posts/:user_id/comment/:comment_id', to: 'replies#create', as: 'reply'
  post  'posts/:user_id/reply/:reply_id',     to: 'replies#re_rep', as: 'r_reply'
  get 'search', to: 'posts#search'
  resources :posts do
    resources :likes, only: [:create, :destroy]
    # resources :comments, only: [:create]
  end
  
  
  get  'user/new',       to: 'users#new',    as: 'u_new'
  post 'user/create',    to: 'users#create', as: 'u_create'
  get  'user/index',     to: 'users#index',  as: 'u_index'
  get  'user/show/:id',      to: 'users#show',   as: 'u_show'
  get  'user/edit',      to: 'users#edit',   as: 'u_edit'
  patch'user/update',    to: 'users#update', as: 'u_up'
  resources :users do
    get :search, on: :collection
  end
  
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  
  # get  '/user/:id/following',  to: 'users#following',  as: 'following_user_path'
  # get  '/user/:id/followers',  to: 'users#followers',  as: 'followers_user_path'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  # get 'messages/index/:sender_id', to:  'messages#index', as: 'm_index'
  # get 'messages/room/:sender_id/:receiver_id', to:  'messages#roomshow', as: 'm_show'
  # post 'send', to: 'messages#create', as: 'send' 
  # resources :messages
  
  resources :relationships,       only: [:create, :destroy]
  
  get 'search_func', to: 'search#search',  as: 'search_func'
  get 'search_s', to: 'search#sato', as: 'sato'
  
  get  'room/index/:id',               to: 'rooms#index',   as: 'room'
  get  'chat/:room_id',                to: 'rooms#chat',    as: 'exist_room'
  get  'chat/:sender_id/:receiver_id', to: 'rooms#chat',    as: 'chat'
  post 'message/send',                 to: 'messages#sending', as: 'm_send'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    if params[:email].present?
      @users = User.where('email LIKE ?', "%#{params[:email]}%")
    else
      @users = User.none
    end
    @user = current_user
    @rooms = Room.where(sender_id: @user.id).or(Room.where(receiver_id: @user.id))
  end
  
  def chat
    @sender = current_user
    p '1==========='
    if params[:receiver_id]
      @receiver = User.find_by(id: params[:receiver_id])
    p '2============'
      @room = room_check(@sender, @receiver)
    end
    if params[:room_id]
    p '3==============='
      @room = Room.find_by(id: params[:room_id])
    end
    if @room
      p "========="
      p @room.id
      p "========="
      @messages = Message.where(room_id: @room.id)
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/chat.html.erb
<h1>
  <% if @room %>
    <% if @room.receiver.id == current_user.id %>
      <%= @room.sender.email %>さんとのメッセージ
    <% else %>
      <%= @room.receiver.email %>さんとのメッセージ
    <% end %>
  <% else %>
    <%= @receiver.email %>さんとのメッセージ
  <% end %>
</h1>


<div class="flex flex-col">
  <% @messages&.each do |message| %>
    <% if message.sender_id == current_user.id %>
    <div class="right flex flex-row mb-8">
    <div class="ml-3 text-sm bg-white py-2 px-4 shadow rounded-xl">
        <p>
          <%= message.content %>
        </p>
      </div>
      <div class="flex items-center justify-center h-10 w-10 rounded-full bg-white flex-shrink-0">
        <% if @sender.profile_image? %>
          <%= image_tag @sender.profile_image.url, width: "87px" %>
        <% else %>
          <%= image_tag ("rails.png") %>
        <% end %>
      </div>
    </div>
    <% else %>
    <div class="flex flex-row-reverse mb-8">
      <div class="flex items-center justify-center h-10 w-10 rounded-full bg-white flex-shrink-0">
        <% if @room.receiver.profile_image? %>
          <%= image_tag @receiver.profile_image.url, width: "87px" %>
        <% else %>
          <%= image_tag ("rails.png") %>
        <% end %>
      </div>
      <div class="ml-3 text-sm bg-white py-2 px-4 shadow rounded-xl">
        <p>
          <%= message.content %>
        </p>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

  <%= form_for(:message, url: m_send_path) do |form| %>
    <%= form.text_area :content, id: "content", rows: "4", class: "form_textarea mb-4" %>
    <% if @room %>
      <%= form.text_field :room_id, class: "hidden hide", value: @room.id %>
    <% else %>
      <%= form.text_field :sender_id, class: "hidden hide", value: @sender.id %>
      <%= form.text_field :receiver_id, class: "hidden hide", value: @receiver.id %>
    <% end %>
    <%= form.submit "メッセージ送信", class: "btn_01" %>
  <% end %>

app/views/rooms/index.html.erb
<h1>メッセージルーム</h1>
  <h2>ユーザー検索</h2>
    <%= form_with url: room_path, method: :get, local: true do |f| %>
      <%= f.text_field :email %>
      <%= f.submit :search %>
    <% end %>
    <table>
      <thead>
        <tr>
          <th>検索結果</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to(user.email, chat_path(sender_id: current_user.id, receiver_id: user.id)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
 
<h2>メッセージ履歴</h2>
<ul>
  <% @rooms.each do | room | %>
    <li>
      <% if @user.id == room.receiver.id %>
        <%= link_to room.sender.email, exist_room_path(room.id) %>
      <% else %>
        <%= link_to room.receiver.email, exist_room_path(room.id) %>
      <% end %>
    </li>
  <% end %>
</ul>