config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'post_new',       to: 'posts#new',    as: 'p_new'
  post 'post_create',    to: 'posts#create', as: 'p_create'
  get  'post_index',     to: 'posts#index',  as: 'p_index'
  get  'post_show/:id',  to: 'posts#show',   as: 'p_show'
  get  'post_edit/:id',  to: 'posts#edit',   as: 'p_edit'
  patch  'post_update/:id',    to: 'posts#update',  as: 'p_up'
  delete 'post_delete/:id',    to: 'posts#destroy', as: 'p_des'
  post  'posts/:post_id/comment',    to: 'comments#create', as: 'p_com'
  post  'posts/:user_id/comment/:comment_id', to: 'replies#create', as: 'reply'
  post  'posts/:user_id/reply/:reply_id',     to: 'replies#re_rep', as: 'r_reply'
  get 'search', to: 'posts#search'
  resources :posts do
    resources :likes, only: [:create, :destroy]
    # resources :comments, only: [:create]
  end
  
  
  get  'user/new',       to: 'users#new',    as: 'u_new'
  post 'user/create',    to: 'users#create', as: 'u_create'
  get  'user/index',     to: 'users#index',  as: 'u_index'
  get  'user/show/:id',      to: 'users#show',   as: 'u_show'
  get  'user/edit',      to: 'users#edit',   as: 'u_edit'
  patch'user/update',    to: 'users#update', as: 'u_up'
  resources :users do
    get :search, on: :collection
  end
  
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  
  # get  '/user/:id/following',  to: 'users#following',  as: 'following_user_path'
  # get  '/user/:id/followers',  to: 'users#followers',  as: 'followers_user_path'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  # get 'messages/index/:sender_id', to:  'messages#index', as: 'm_index'
  # get 'messages/room/:sender_id/:receiver_id', to:  'messages#roomshow', as: 'm_show'
  # post 'send', to: 'messages#create', as: 'send' 
  # resources :messages
  
  resources :relationships,       only: [:create, :destroy]
  
  get 'search_func', to: 'search#search',  as: 'search_func'
  get 'search_s', to: 'search#sato', as: 'sato'
  
  get  'room/index/:id',               to: 'rooms#index',   as: 'room'
  get  'chat/:room_id',                to: 'rooms#chat',    as: 'exist_room'
  get  'chat/:sender_id/:receiver_id', to: 'rooms#chat',    as: 'chat'
  post 'message/send',                 to: 'messages#sending', as: 'm_send'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    has_many :comments
    has_many :replies, class_name: 'Reply', foreign_key: :user_id, dependent: :destroy
    default_scope -> { order(created_at: :desc) }
    mount_uploader :picture, PictureUploader
    validates :title, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 255 }
    validates :user_id, presence: true
    validate  :picture_size
    
    def self.search(keyword)
      where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
    end
    
    private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :index, :show]
  before_action :correct_user,   only: [:update, :destroy]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Micropost created!"
      redirect_to p_index_path
    else
      render :new
    end
  end
  
  def index
    p 'index============='
    @posts = Post.all
    p 'index_end==========='
  end
  
  def show
    p 'show_start========================='
    @post = Post.find(params[:id])
    @like = Like.new
    @comments = @post.comments
    @comment = Comment.new
    @reply = Reply.new
    p 'end========================='
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
      redirect_to p_show_path
    else
      render :edit
    end
  end
  
  def destroy
    p 'des_start========================='
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:success] = "post deleted"
    redirect_to u_show_path(current_user)
    p 'des_end========================='
  end
  
  def search
    @posts = Post.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :picture)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container" style="margin-top: 15px">
    <%= form_for(@post, url: p_up_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        
        <%= f.label :content %>
        <%= f.text_field :content, class: 'form-control' %>
        
        <%= f.submit "編集", class: "btn btn-primary btn-lg btn-lg"%>
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="container" style="margin-top: 15px">
  <div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.submit "検索" %>
  <% end %>
  </div>
  
  <div class="post-list">
    <% @posts.each do |post| %>
      <%= post.title %>
    <% end %>
  </div>
  
    <h1>投稿一覧</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">title</th>
      <th scope="col">created</th>
      <th scope="col">updated</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td scope="row"><%= post.id %></td>
      <td><%= link_to post.title, p_show_path(post.id) %></td>
      <td><%= post.created_at %></td>
      <td><%= post.updated_at %></td>
    </tr>
    <% end %>
  </tbody>  
</table>
  </div>

app/views/posts/new.html.erb
<div class="container" style="margin-top: 15px">
    <%= form_for(@post, url: p_create_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        
        <%= f.label :content %>
        <%= f.text_field :content, class: 'form-control' %>
        
        <%= f.submit "投稿", class: "btn btn-primary btn-lg btn-lg"%>
        <span class="picture">
         <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </span>
    <% end %>
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>



  <!--<div class="container" style="margin-top: 15px">-->
  <!--  <form class="new_post" id="new_post" action="/post_new" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="LN0KqEgmG7DVyNmqyiI75BGFfarMSg+v05tk7fMa+0eumbxtoC5HPUsz0cC6i9dtNVKTFgwK88kArCe6QaMPVw==">-->
  <!--    <div class="form-group">-->
  <!--      <label for="exampleInputEmail1">Title</label>-->
  <!--      <input class="form-control" id="title" oninput="count_text()" type="text" name="post[title]">-->
  <!--    </div>-->
  <!--    <div class="form-group">-->
  <!--      <label for="exampleInputEmail1">Content</label>-->
  <!--      <textarea class="form-control" id="text" oninput="count_text()" name="post[content]"></textarea>-->
  <!--    </div>-->
  <!--      <button class="btn btn-primary btn-lg" id="btn" disabled="">投稿</button>-->
  <!--  </form>-->
    
<!--<style>-->
<!--  input[type="submit"]:disabled{-->
<!--    background: #ccc;-->
<!--  }-->
<!--</style>-->

<!--<script>-->
<!--  function count_text(){-->
<!--    const title = document.getElementById("title").value.length;-->
<!--    const txt = document.getElementById("text").value.length;-->
<!--    if(title > 1 && txt  > 1){-->
<!--      console.log(title);-->
<!--      document.getElementById("btn").removeAttribute("disabled");-->
<!--    }else{-->
<!--      console.log("test")-->
<!--      document.getElementById("btn").setAttribute("disabled", true);-->
<!--    }-->
<!--  }-->
<!--</script>-->

app/views/posts/show.html.erb
<div class="container" style="margin-top: 15px">
  <div class="card">
    <div class="card-header">
      <%= @post.id %>
    </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @post.content %></p>
      <%= image_tag @post.picture.url if @post.picture? %>
      <footer class="blockquote-footer">created_at: <cite title="Source Title"><%= @post.created_at %></cite></footer>
    </blockquote>
  </div>
    <% if current_user?(@post.user) %>
      <%= link_to "edit", p_edit_path(@post.id) %>
      <%= link_to "delete", p_des_path(@post.id), method: :delete %>
    <% end %>
  </div>
  <h3>いいね件数: <%= @post.likes.count %></h3>
    <% if current_user.already_liked?(@post) %>
      <a href="/posts/<%= @post.id %>/likes/<%= current_user.id%>" data-method="delete"><i class="fas fa-heart"></i>取り消し</a>
      <!--<%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>-->
    <% else %>
      <a href="/posts/<%= @post.id %>/likes" data-method="post"><i class="far fa-heart"></i>お気に入り</a>
      <!--<%= button_to 'いいね', post_likes_path(@post) %>-->
    <% end %>
    <h2>いいねしたユーザー</h2>
    <% @post.liked_users.each do |user| %>
      <li><%= user.email %></li>
    <% end %>
    
    <h2>コメント一覧</h2>
    
      <% @comments.each do |c| %>
        <div class="card">
          <div class="card-header">
            <a href="/users/<%= @post.user.id %>"><%= c.user.email %></a>
          </div>
          <div class="card-body">
            <%= c.content %>
          </div>
          <%= form_for(@reply, url: reply_path(comment_id: c.id, user_id: current_user.id)) do |f| %>
            <%= f.text_field :reply %>
            <br>
            <%= f.submit 'コメントに返信する' %>
          <% end %>
        </div>  
        
              
            <% c.replies.each do |re| %>
              <div class="card rep">
                <div class="card-header">
                  <%= re.user.email %>
                </div>
                <div class="card-body">
                  <%= c.user.email %>さんへの返信
                  <br>
                  <%= re.reply %>
                </div>
                <%= form_for(@reply, url: reply_path(comment_id: c.id, user_id: current_user.id)) do |f| %>
                  <%= f.text_field :reply %>
                  <br>
                  <%= f.submit 'コメントに返信する' %>
                <% end %>
              </div>
            <% end %>
      <% end %>
    
    
    
    <div class="card my-1"> 
      <div class="card-body">
        <p class="font-weight-bold">Comments</p>
        <%= form_for(@comment, url: p_com_path(@post.id)) do |f| %>
          <%= f.text_field :content %>
          <br>
          <%= f.submit 'コメントする' %>
        <% end %>
      </div>
    </div>

</div>